### ISSUE TITLE
[SingleCell]  AssertionError in Step 10 Error correction

### ISSUE THREAD

**Issue by ksahlin** [Magdoll/cDNA_Cupcake#158]
Hi Liz,

I run 

```
python /home/kris/source/cDNA_Cupcake/singlecell/UMI_BC_error_correct.py dedup.annotated.csv dedup.corrected.csv
```
where `dedup.annotated.csv` is the output file from `collate_FLNC_gene_info.py`, and I get

```
Traceback (most recent call last):
  File "/home/kris/source/cDNA_Cupcake/singlecell/UMI_BC_error_correct.py", line 187, in <module>
    main(args.input_csv, args.output_csv, shortread_bc, args.only_top_ranked, bc_repair_dict)
  File "/home/kris/source/cDNA_Cupcake/singlecell/UMI_BC_error_correct.py", line 134, in main
    bc_merge_map = error_correct_BC_or_UMI(recs_by_gene[gene], 'BC')
  File "/home/kris/source/cDNA_Cupcake/singlecell/UMI_BC_error_correct.py", line 95, in error_correct_BC_or_UMI
    if edit_distance(bc_sorted[i], bc_sorted[j]) <= threshold:
  File "/home/kris/source/cDNA_Cupcake/singlecell/UMI_BC_error_correct.py", line 73, in edit_distance
    assert len(seq1)==len(seq2)
AssertionError
```

Let me know if you need any other information to trace down this bug.

**Comment by Magdoll** [comment]
Hi @ksahlin 
I think I know where this is coming from - did you run `isoseq3 dedup` with default? it's possible some of the single cell barcodes were allowed to miss 1bp resulting in barcodes having different lengths and that defied this script's assumption.

I'm overdue for over-hauling the default parameters for `isoseq dedup`, but in the meantime can you try running it again with

```
isoseq3 dedup fltnc.bam dedup.bam --verbose --max-tag-mismatches 1 --max-tag-shift 0 --min-concordance-perc 99
```

I'm not entirely sure this will result in all BCs being same length (because `isoseq3 tag` may be the ultimate place I need to address this). Let me know. I need to fix this part.
Thanks,
-Liz

**Comment by ksahlin** [comment]
Thanks for the suggestion. I just restarted the pipeline at the `isoseq3 dedup` step with the suggested parameters. I will let you know how it goes.

I also downloaded the `dedup.annotated.csv` file(s) in the meantime since you say that the error correction step is optional. One thing I notice is that the `dedup.annotated.csv` files produced between different aligners is fairly large (minimap2 (68Mb) deSALT/deSALT_GTF (~36Mb) and uLTRA (~70Mb)). Have you seen this before? 

This is the first time I'm analyzing single-cell iso-seq so would be happy to take ideas for how to visualize the files (and their differences). Do you have any python or R scripts ready to use? Or suggestions for first interesting things to plot? Happy for any suggestions here (or quick zoom if easier for you)!

Best,
K
