### ISSUE TITLE
ModuleNotFoundError: No module named 'cupcake.tofu' after installing cdna_cupcake in conda subenv

### ISSUE THREAD

**Issue by LilyLuyang** [Magdoll/cDNA_Cupcake#246]
I created conda subenv based on python3.7 and also installed cdna_cupcake and its denpendencies as well, but when testing if it's successful, the erroe is as follows:
File "~/.conda/envs/py37/bin/collapse_isoforms_by_sam.py", line 26, in <module>
    from cupcake.tofu.utils import check_ids_unique
ModuleNotFoundError: No module named 'cupcake.tofu'

Could you please give some prompts to resolve it?
Thanks.

Lily

**Comment by LilyLuyang** [comment]
Hi,

I just solved this issue through running: python setup.py build & python setup.py install to install the cupcake here. After that, I encountered other errors as described below:

Therefore, I just recreate conda environment, while another question occurred: 'pkg_resources.DistributionNotFound: The 'sklearn' distribution was not found and is required by cupcake', so I tried several ways to address it. Finally, it works after changing 'sklearn' into 'scikit-learn' on line 40 in setup.py, and 'python setup.py build & python setup.py install' to configure the running environment for the cupcake.
After installation is complete, confirm the cupcake scripts are in your bin path: 'collapse_isoforms_by_sam.py -h', and the usage will occur on the screen, which means it works normal.

Hope it can help other users.

Lily

**Comment by tky199996** [comment]
> 你好，
> 
> 我刚刚通过运行以下命令解决了这个问题： python setup.py build & python setup.py install 在此处安装纸杯蛋糕。之后，我遇到了其他错误，如下所述：
> 
> 因此，我只是重新创建 conda 环境，同时出现了另一个问题：'pkg_resources.DistributionNotFound: The 'sklearn' distribution was not found and is required by cupcake'，所以我尝试了几种方法来解决它。最后，将setup.py中第40行的“sklearn”更改为“scikit-learn”，并“python setup.py build & python setup.py install”配置cupcake的运行环境后就可以工作了。 安装完成后，确认cupcake脚本在你的bin路径中：'collapse_isoforms_by_sam.py -h'，屏幕上就会出现使用情况，这意味着它可以正常工作。
> 
> 希望它可以帮助其他用户。
> 
> 百合

Hello, I have recently encountered some difficulties when using SQANTI3 and cDNA_Cupcake. For some reasons, I need to use SQANTI3 and cDNA_Cupcake at the same time. I installed SQANTI3 and cDNA_Cupcake according to the installation requirements. In order to ensure that the two will not interfere with each other, I created I created two conda environments and ran them separately. I once ran both software successfully, but I didn’t know what environment variables were changed the next day, so that the following error occurred when running funsion_finder.py, but when I switched to a new environment and ran SQANTI3 can run successfully, can anyone help me, I want to know how can I run fusion_finder.py successfully？could you help me?
![Uploading 微信图片_20240320152250.png…]()

**Comment by Magdoll** [comment]
Hi @tky199996  - 
Cupcake in this repo is no longer maintained. Did you use the fork from SQANTI3 repo?
https://github.com/ConesaLab/SQANTI3/wiki/Dependencies-and-installation#install4

If so, I'll go look at how we can remove Cupcake dependency in SQANTI3.

For fusion finding, please use the newer better software like:
https://github.com/PacificBiosciences/pbfusion
https://github.com/TrinityCTAT/CTAT-LR-fusion
