### ISSUE TITLE
error in chaining fusion transcripts

### ISSUE THREAD

**Issue by fantastycrane** [Magdoll/cDNA_Cupcake#30]
Hi, @Magdoll 

I ran into an error while chaining fusion transcripts:
"""
ERROR! more than one possible candidate in match_fusion_record! DEBUG.
MATCHED: ['PBfusion.114', 'PBfusion.210']
"""

Information of two involved transcripts are given below.
"""
1       PacBio  transcript      161285514       161288653       .       -       .       gene_id "PBfusion.114"; transcript_id "PBfusion.114.1";
1       PacBio  exon    161285514       161288653       .       -       .       gene_id "PBfusion.114"; transcript_id "PBfusion.114.1";
2       PacBio  transcript      7852284 7853099 .       -       .       gene_id "PBfusion.114"; transcript_id "PBfusion.114.2";
2       PacBio  exon    7852284 7853099 .       -       .       gene_id "PBfusion.114"; transcript_id "PBfusion.114.2";

1       PacBio  transcript      161285514       161288251       .       -       .       gene_id "PBfusion.210"; transcript_id "PBfusion.210.1";
1       PacBio  exon    161285514       161288251       .       -       .       gene_id "PBfusion.210"; transcript_id "PBfusion.210.1";
2       PacBio  transcript      7852289 7853099 .       -       .       gene_id "PBfusion.210"; transcript_id "PBfusion.210.2";
2       PacBio  exon    7852289 7853099 .       -       .       gene_id "PBfusion.210"; transcript_id "PBfusion.210.2";
"""
PBfusion.114 and PBfusion.210 are two different fusion transcripts while PBfusion.114.2 and PBfusion.210.2 are identical. Is this the cause of this issue? And how can we solve this? Thanks.

**Comment by Magdoll** [comment]
Hi @fantastycrane ,

This is a deliberate error thrown to notify the user that the script cannot make an unambiguous decision in chaining fusion transcripts across samples.

In the case you provided, `PBfusion.114` and `PBfusion.210` are two fusions that each consist of two single-exon segments *and* these two single-exon segments overlap. So, the script cannot make a decision in this case for chaining because there are multiple candidates to chain with.

There is no easy solution at this point. The purpose of the script throwing a warning is to ask the user to manually examine and remove these conflicts. You would either remove one of the two fusions or create a new fusion that represents the two fusions in some manner.
