### ISSUE TITLE
Error about installing Cupcake (running 'python setup.py install')

### ISSUE THREAD

**Issue by ClearloveMiao** [Magdoll/cDNA_Cupcake#31]
Hi, @Magdoll ,
I have tried to install Cupcake. But when I run `python setup.py install`, it reported such errors:
![image](https://user-images.githubusercontent.com/37678675/38938939-5caad146-4359-11e8-998f-f4d62fd9b30c.png)

So what can I do now to deal with this error? Thanks for any suggestions!

**Comment by Magdoll** [comment]
Hi @ClearloveMiao ,
Sorry but can you update to Cupcake version 5.3 (which is tag [tofu2_v21](https://github.com/Magdoll/cDNA_Cupcake/tree/tofu2_v21)) because (1) the update supports the latest sequencing chemistry and (2) the lzo dependency likely went away. If it still shows up, we can troubleshoot it for the latest version.


Thanks,
--Liz
