### ISSUE TITLE
collapse_isoforms_by_sam.py runtime error

### ISSUE THREAD

**Issue by paprikachan** [Magdoll/cDNA_Cupcake#38]
Hi,

I have already updated to the v5.8.

When I run collapse_isoforms_by_sam.py, error occured:

```
$tail runtime.log
alt. junction found at 514
alt. junction found at 804
Traceback (most recent call last):
  File "/home/chenlingxi/mnt/chenlingxi/lib/tools/anaconda2/bin/collapse_isoforms_by_sam.py", line 245, in <module>
    main(args)
  File "/home/chenlingxi/mnt/chenlingxi/lib/tools/anaconda2/bin/collapse_isoforms_by_sam.py", line 190, in main
    for recs in iter: # recs is {'+': list of list of records, '-': list of list of records}
  File "/home/chenlingxi/mnt/chenlingxi/lib/tools/anaconda2/lib/python2.7/site-packages/cupcake/tofu/branch/branch_simple2.py", line 97, in iter_gmap_sam
    ignored_fout.write("{0}\tCoverage {1:.3f} too low.\n".format(r.qID, r.qCoverage))
ValueError: Unknown format code 'f' for object of type 'str'
```

There are already some outputs:
```
$ls
OC001T.hq_isoforms.collapsed.gff  OC001T.hq_isoforms.collapsed.group.txt  OC001T.hq_isoforms.ignored_ids.txt  runtime.log
```

How to fix it? Thanks.

**Comment by paprikachan** [comment]
I changed  {1:.3f} to {1} in cupcake/tofu/branch/branch_simple2.py, and problem solved. Plus I am using minimap2 aligned bam.

**Comment by Magdoll** [comment]
@paprikachan ,

Even if that solves the problem, I think it's possible some records in your SAM file is not correct. This error happens when the SAM file is not sorted or is corrupted/incomplete.

--Liz

**Comment by paprikachan** [comment]
@Magdoll  I checked the Sam file,  it's sorted but there are some unmapped reads at the end of file. So, the unmapped reads should be filtered out, right?

**Comment by paprikachan** [comment]
@Magdoll 
Hi, I have removed the ummapped reads and successfully completed the **collapse** and **count** steps with no error message.

While, when I run **filter** command:
```
filter_away_subset.py $prefix
```
Error occurs:
```
The number of PBID records in the files disagree! Sanity check failed.
# of PBIDs in /home/chenlingxi/mnt/chenlingxi/workspace/FS_Projects/WHOC.Sequel_PB.batch01/Isoform/cupcake_minimap2/OC001T/OC001T.hq_isoforms.collapsed.rep.fq: 14779
# of PBIDs in /home/chenlingxi/mnt/chenlingxi/workspace/FS_Projects/WHOC.Sequel_PB.batch01/Isoform/cupcake_minimap2/OC001T/OC001T.hq_isoforms.collapsed.gff: 14779
# of PBIDs in /home/chenlingxi/mnt/chenlingxi/workspace/FS_Projects/WHOC.Sequel_PB.batch01/Isoform/cupcake_minimap2/OC001T/OC001T.hq_isoforms.collapsed.abundance.txt: 12143
```

It seems there are problems in **count** step. I run count commands like:
```
get_abundance_post_collapse.py  $prefix $cluster_fn
```
whileI didn't append the cluster_id prefix before running **count**, 
is this the cause of error?

Thanks a lot.

**Comment by Magdoll** [comment]
Hi @paprikachan ,

1. The unmapped reads should not have been a problem unless you didn't sort using the following 

```
sort -k 3,3 -k 4,4n input.sam > input.sorted.sam
```

This sorts all unmapped reads in the *beginning*, not the end of the SAM file. Since you say the unmapped reads were at the end of the files, the sorting is probably the issue. 

That said, since you removed the unmapped alignments from SAM file, I don't think they would affect the collapse results (because the collapse script simply ignores them as long as they are properly sorted to the beginning).


2. re: the discrepancy between the count file. 

Can you check the number of lines in the group.txt file?

```
wc -l OC001T.hq_isoforms.group.txt
```

The number of lines in here should also be exactly 14779.


(side note: this sanity check is necessary, and I've now seen enough sanity check fails that I should figure out a way for you guys to not experience it, rather have the collapse or get_abundance step throw the proper warning if the outputs were not consistent.)

**Comment by paprikachan** [comment]
Hi @Magdoll,

Thanks for your reply. For the discrepancy between the count files. I figure out why.

I use the old version of **cluster**, and run it with multiple bins. So I need to append bin_index into the cluster prefix in both cluster_report.csv and fastq id.
