### ISSUE TITLE
abundance metric

### ISSUE THREAD

**Issue by paprikachan** [Magdoll/cDNA_Cupcake#39]
Hi @Magdoll ,

The abundance file gives 6 measurements, which one do you recommend to use as gene expression metric in upstream analysis? Or should I do other nomarlization like TPM, RPKM or FPKM?
```
# count_fl: Number of associated FL reads
# count_nfl: Number of associated FL + unique nFL reads
# count_nfl_amb: Number of associated FL + unique nFL + weighted ambiguous nFL reads
# norm_fl: count_fl / total number of FL reads
# norm_nfl: count_nfl / total number of FL + unique nFL reads
# norm_nfl_amb: count_nfl_amb / total number of all reads
```

Thanks a lot.

**Comment by Magdoll** [comment]
Hi @paprikachan ,

The `count_` are the raw counts. The `norm_` are normalized per the denominator shown in comments.

The difference between using `norm_fl`, `norm_nfl`, and `norm_nfl_amb` depends on whether you trust non-full-length (nFL). Based on very limited data I've seen in the past, using any of the three metrics have largely the same results. I would recommend staying with `norm_fl`. Since it is already normalized by the total number of FL reads, you can multiply by this number by a million to approximate TPM. 

*NOTE* in the upcoming Iso-Seq3, nFL reads will not be used and therefore you will always only use `count_fl` and `norm_fl`.
