### ISSUE TITLE
run fusion_finder.py on collapsed fastq and sam found no fusion event

### ISSUE THREAD

**Issue by paprikachan** [Magdoll/cDNA_Cupcake#40]
Hi @Magdoll ,

I run fusion_finder.py on both collapsed data and uncollapsed data:
 - with uncollapsed data, the script found 25 fusion events
 - with collapsed data, the script found no fusion event

I cannot figure out why, in my understanding, the results should be the same for collapsed or uncollapsed data as input.

Thanks a lot.

**Comment by Magdoll** [comment]
Hi @paprikachan ,

Collapsed data (run through `collapse_isoforms_by_sam.py`) using default parameters will always have zero fusion, because the default parameter uses a coverage cutoff (`-c`) of 0.99. So by definition, all fusion transcripts will be ignored. `fusion_finder.py` should be run on non-collapsed SAM file. 

Hope that makes sense :) It was intentionally designed this way.

--Liz
