### ISSUE TITLE
differences in output for preCluster.py depending on batchsize

### ISSUE THREAD

**Issue by HenrivdGeest** [Magdoll/cDNA_Cupcake#45]
I have an ISOSeq dataset which contains 71k sequences.
before running Cogent, I want to run the preCluster step. 
However if I play with the --num_seqs_per_batch parameter, I get different outputs. I do **[edit]_not_ [/edit]** fully understand why this is.
With the batch size at 5000 I get ~7000 clusters, with also around ~7000 orphan reads.
Setting the batch size to 500000, I get ~23k orphans reads and 11k clusters.
I can see from the partitioning csv file that the cluster with the latter setting are smaller compared to the small batch size parameter.
The clusters might get divided more with the run_mash script afterwards, but the orphans are untouched as far as I understand. 

My question, does this really matter and if so, how to determine the batchsize in run_preCluster.py?

**Comment by Magdoll** [comment]
This is because I've set an limit on how many records a single minimap2 run can report, currently set to `-N 2000000` as seen in [code here](https://github.com/Magdoll/cDNA_Cupcake/blob/master/cupcake2/ice2/AlignerRunners.py#L9). 

So, when you put in a big batch like 500k sequences, even if every sequence is homologous, you'd get an average of 4 hits per sequence. This `-N` limit is necessary to prevent minimap2 from blowing up in targeted Iso-Seq cases while still maintaining a reasonable tradeoff with eventual pre-cluster size.

The default batch size of 1000000 was selected to work well for a whole transcriptome (high diversity) case, specifically for inputs of FL reads though. Your input is supposedly 71k HQ isoforms that already has redundancy reduced, so the diversity would be even higher than the usual case.

I'm curious - did you notice a significant run-time difference between a batch size of 5000 vs 500000?

--Liz

**Comment by Magdoll** [comment]
Hi @HenrivdGeest ,

My intuition is actually the opposite - the smaller the batch, the less orphans, but probably there's a balance.

Because of the `-N` (reporting limit) in minimap2, when the batch is smaller, each hit will be reported and clustered together --> why small batches result in fewer orphans.

However, when the batch size is too small, it's also possible no clusters get formed because by chance nothing is a hit when the batch is too small.

Below is an example of a Cogent input. All input is HQ isoforms. There are 641,653 HQ isoforms. It confirms my hypothesis. When the batch size is too high (500k, when `-N` is set to 2000k, meaning on average only 4 hits are reported per read), the number of orphans is very high. The batch size between 50-200k don't seem very different.

batchsize_50k/preCluster_out.orphans.fasta:17168
batchsize_100k/preCluster_out.orphans.fasta:19309
batchsize_200k/preCluster_out.orphans.fasta:16382
batchsize_500k/preCluster_out.orphans.fasta:71678
