### ISSUE TITLE
Annotating unique isoforms

### ISSUE THREAD

**Issue by kushalsuryamohan** [Magdoll/cDNA_Cupcake#47]
Hi @Magdoll,

First time user of Cupcake here.

I have two separate questions - 
1. I have Isoseq CCS runs for two separate smrt cells run for a single tissue. Do I combine the HQ_isoforms.fasta of both runs and then run the collapse_isoforms scripts and the remaining downstream steps or should I collapse isoforms individually, get count information and then do the chaining? 

2. I have a reference genome and I have mapped the HQ_isoforms to this but I would like to use the annotation file (GFF) as well to know the gene names. Is there a way to do this or should I just use bedtools to intersect the gff file after collapsing isoforms?

Many thanks!

**Comment by Magdoll** [comment]
Hi @kushalsuryamohan ,

(1) Please specify what Iso-Seq on which SMRT Link version (or command line) you are running? Our latest release is the SMRT Link 6.0 release and we recommend the Iso-Seq 3 analysis.

(2) Do you mean you have 2 SMRT cell and each is a different tissue (so you have 2 tissues), or you have 2 SMRT cells each coming from the same tissue?

In general, we always recommend pooling data from the same species because it increases coverage for shared transcripts and would result in higher yield. However, if you choose to continue with the current output, then combining the HQ isoforms fastq and running collapse is likely the easiest option.

For future reference, Iso-Seq 3 with Mapping in SMRT Link 6.0 already contains the mapping and collapse step provided by Cupcake. So choosing Iso-Seq 3 with Mapping in the future would eliminate the need to run Cupcake and get you directly to GFF files for annotation.

(3) The Conesa lab has developed a SQANTI software package that can compare Iso-Seq mapped output against a known annotation. The reference annotation would have to be provided in a GTF format:
https://bitbucket.org/ConesaLab/sqanti/


--Liz
