### ISSUE TITLE
the content of primers.fasta

### ISSUE THREAD

**Issue by wenmm** [Magdoll/cDNA_Cupcake#58]
I see the primers.fasta here is : 
>5p
AAGCAGTGGTATCAACGCAGAGTGAATGGG
>3p
GTACTCTGCGTTGATACCACTGCTT
but in the isoseq3 README the primers.fasta is:
>primer_5p
AAGCAGTGGTATCAACGCAGAGTACATGGGG
>primer_3p
AAGCAGTGGTATCAACGCAGAGTAC

is there anything wrong????

**Comment by Magdoll** [comment]
Hi @wenmm ,

lima (the demultiplexing tool) used to detect and remove the cDNA primers can accept primers in both directions.

Hence, the `primer_3p` and `3p` are the same, just reverse complement of each other.

The Clontech SMARTer `5p` and `primer_5p` are the same too, one has an extra `G` because the RT step isn't precise and even though it's technically `ATGGG`, I've usually recommended `ATGGGG` to remove the extra `G`. Both versions can be used.
