### ISSUE TITLE
No module named pClique when running run_IceInit2.py

### ISSUE THREAD

**Issue by defendant602** [Magdoll/cDNA_Cupcake#60]
Hi, Liz:
When I run run_IceInit2.py in cDNA_Cupcake(version 6.5), I got this error:
Traceback (most recent call last):
  File "MyPath/cDNA_Cupcake/build/scripts-2.7/run_IceInit2.py", line 5, in <module>
    from cupcake2.ice2.IceInit2 import IceInit2
  File "MyPath/cDNA_Cupcake/cupcake2/ice2/IceInit2.py", line 24, in <module>
    import cupcake.ice.pClique as pClique
ImportError: No module named pClique

When I go to the subdir MyPath/cDNA_Cupcake/cupcake/ice, I found no files named pClique.py in there. The files in the subdir are "find_ECE.c  find_ECE.pyx  ice_align_core.py  __init__.py  __init__.pyc  setup2.py". 

Is it because I didn't install cDNA_Cupcake correctly ? or how should I solve this problem ?

Looking forward to your reply. Thanks!

**Comment by Magdoll** [comment]
Hi @defendant602 ,

The ToFU/ICE part of Cupcake is currently not being supported due to lots of dependency changes in the official PacBio software. (you will notice the tutorial for ToFU is now *OBSOLETE*)

If you are processing Iso-Seq data, please use [Iso-Seq3 from BioConda](https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Tutorial:-Installing-and-Running-Iso-Seq-3-using-Conda) or SMRT Analysis/SMRT Link.

That said, I may find some time in the future to support it again. When that happens, I will update the code base & wiki.

Thanks,
--Liz
