### ISSUE TITLE
Unexpected Chain Samples Results

### ISSUE THREAD

**Issue by j-baller** [Magdoll/cDNA_Cupcake#7]
Running: 
`chain_samples.py CONFIG_FILE count_nfl` 
I am getting results that don't seem to be in line with the IGV image of the same regions. In particular, I'm seeing ~1000 to ~10 count differentials between samples for some some regions via chain samples, when the IGV image shows about 160 reads in both samples (almost all full length). Furthermore while I would assume that the count_fl results would be based on the number of input reads, I only have about 14,000 input reads, but the chain_samples.py columns sum to around 140,000. 

These results seem unexpected to me, is this a bug or am I misunderstanding something?

**Comment by Magdoll** [comment]
Hi @j-baller ,

The count file numbers (fields like count_fl, count_nfl), show the number of supporting full-length/non-full-length CCS reads. Since each CCS read is a single molecule, it shows the number of supporting single molecules.

I don't know what your input to chaining is, but I am assuming it is NOT CCS reads but rather after running Iso_Seq cluster, you obtain the HQ (high-quality) isoforms, correct?

Each HQ isoform is the polished consensus of a "cluster" of FL and nFL CCS reads. Hence, each HQ isoform itself is usually supported by multiple (single molecule) reads.

The count file doesn't show the number of supporting HQ isoforms - that number is rather meaningless - rather, it shows for each unique isoform (I assume you mapped the HQ isoforms to a genome and collapsed them) the number of supporting CCS (single molecule) reads. 

If this is still confusing, or you would like to confirm you are indeed looking at CCS reads as counts, please send me some more detail about what went into your chaining? What are the sequence IDs?

--Liz

**Comment by j-baller** [comment]
Hi Liz,
Your response makes perfect sense. I had forgotten about the inclusion of the cluster_report as a source of CCS reads.

Thank you for your response,
Josh
