### ISSUE TITLE
What is the idea of using Cupcake ToFU for collapsing ISO-seq hq isoforms?

### ISSUE THREAD

**Issue by juheon** [Magdoll/cDNA_Cupcake#73]
I am currently using ISO-seq3 which includes "clustering" step and I expect the clustering step will eliminate all redundant isoforms.

How does Cupcake ToFU further eliminate redundant isoforms with/without the genome reference?

I could find how I run the script but not how it works..

**Comment by Magdoll** [comment]
Hi @juheon ,

The collapse script deals with possible 5' degradation - which by IsoSeq3 standards, can be considered different isoforms.

If you map the HQ isoforms (IsoSeq3 output) to a reference genome and run collapse and compare the before- and after- collapse results, it should be pretty obvious.

**Comment by juheon** [comment]
I found the helpful description for Cupcake Tofu collapse: 
https://github.com/GenomeRIK/tama/wiki/Tama-Collapse. 
Section "Detailed explanation of TAMA Collapse" contains the description of Cupcake Tofu collapse.

**Comment by eadriaensen** [comment]
This information was very interesting to me. Thank you both!

However, it remains unclear to me what the default mode of collapsing is by CupCake, using the `collapse_isoforms_by_sam.py` script. Is it TSSC or ECC ?

Unfortunately, comparing before- and after- collapse results is not very obvious to me, since my before results are FLNC reads (and not clustered isoforms). I don't cluster in my workflow.

Apologies if it's inappropriate to continue a question on a closed issue. I am relatively new to Github..

Best,
Eva

**Comment by Magdoll** [comment]
HI @eadriaensen ,

With FLNC you can still look at the before- and after- collapse. Both Cupcake & TAMA collapse works on FLNC *and* post-cluster high-quality (HQ) isoforms.

The default in `collapse_isoforms_by_sam.py` is to collapse degraded transcripts into longer ones. The behavior can be turned off using `--dun-merge-5-shorter`.

--Liz
