### ISSUE TITLE
demux_by_barcode_groups.py

### ISSUE THREAD

**Issue by tomasflyo** [Magdoll/cDNA_Cupcake#82]
#81  

Hi @Magdoll ,

I pip uninstalled cupcake and removed the git folder.
After git cloning the cDNA_Cupcake directory from scratch, building + installing setup.py, and then running the demux_by_barcode_groups.py script I got this error msg:

> Traceback (most recent call last):
>   File "demux_by_barcode_groups.py", line 8, in <module>
>     from cupcake.io.BioReaders import GMAPSAMReader
>   File "/home/labs/shlush/tomasfly/.venvs/lsl/lib/python3.6/site-packages/cupcake-7.7-py3.6-linux-x86_64.egg/cupcake/io/BioReaders.py", line 311
>     raise Exception, "Unrecognized cigar character {0}!".format(type)
>                    ^
> SyntaxError: invalid syntax

Thanks,
Tom

**Comment by Magdoll** [comment]
Hi @tomasflyo 

That syntax error should not exist. Also this indicates these's something odd with your SAM file. Instead of chasing one error at a time, can you please share the input data with me confidentially so I can just run the commands and try it out?

Please give me an email so I can request file upload.

Thanks,
--Liz

**Comment by tomasflyo** [comment]
Hi Liz,

Sent a share link to your pacificbiosciences email

Thanks
Tom

**Comment by Magdoll** [comment]
Minor bug discovered and updated to v7.9. Works now.
